### ISSUE TITLE
How to apply multiple Pools with different PHP-Versions to different servers?

### ISSUE THREAD

**Issue by davidak** [NBZ4live/ansible-php-fpm#23]
We have about 200 Servers and some should have multiple PHP-versions for different webspaces.

That should be implemented in a Role. How can i do that?

I thought about this structure in the `host_vars`

```
webspaces:
  - name: web1
    password: "{{ vault_ssh_web1_password }}"
    php: 5.6
    php_ini:
      - 'memory_limit: 128M'
  - name: web2
    password: "{{ vault_ssh_web2_password }}"
    php: 7.0
```

and this in the Role **webspace**

```
- name: create PHP 7.0 FPM Pools
  debug: msg="{{ item.name }}"
  when: "item.php == 7.0"
  with_items: "{{ webspaces }}"

- name: create PHP 5.6 FPM Pools
  debug: msg="{{ item.name }}"
  when: "item.php == 5.6"
  with_items: "{{ webspaces }}"
```

but you can't use `with_items` with roles (https://github.com/ansible/ansible/issues/12623#issuecomment-145312563)

**Comment by davidak** [comment]
I build a wrapper role like this:

meta/main.yml
```
dependencies:
  - { role: nbz4live.php-fpm,
      php_fpm_version: 5.6,
      php_fpm_pool_defaults: "{{ php56_fpm_pool_defaults }}",
      php_fpm_default_pool: "{{ php56_fpm_default_pool }}",
      php_fpm_pools: "{{ php56_fpm_pools }}",
      php_fpm_ini: "{{ php56_fpm_ini }}",
      php_fpm_config: "{{ php56_fpm_config }}"
    }
```

defaults/main.yml
```
php56_fpm_pool_defaults:
    pm: dynamic
    pm.max_children: 10
    pm.start_servers: 2
    pm.min_spare_servers: 1
    pm.max_spare_servers: 3
php56_fpm_default_pool:
  delete: False
  name: www.conf
php56_fpm_pools:
   - name: www
     user: www-data
     group: www-data
     listen: 127.0.0.1:9566
php56_fpm_ini:
   - option: "date.timezone"
     section: "PHP"
     value: "Europe/Berlin"
   # MySQL Socket
   - option: "mysql.default_socket"
     section: "MySQL"
     value: "/var/run/mysqld/mysqld.sock"
   - option: "pdo_mysql.default_socket"
     section: "Pdo_mysql"
     value: "/var/run/mysqld/mysqld.sock"
   - option: "mysqli.default_socket"
     section: "MySQLi"
     value: "/var/run/mysqld/mysqld.sock"
php56_fpm_config: []
```

So you can specify the pools in the `host_vars`:
```
php56_fpm_pools:
   - name: www
     user: www-data
     group: www-data
     listen: 127.0.0.1:9566
   - name: web1
     user: web1
     group: web1
     listen: 127.0.0.1:9001
```
