### ISSUE TITLE
include must be the last line in php-fpm.conf

### ISSUE THREAD

**Issue by infernix** [NBZ4live/ansible-php-fpm#5]
If it isn't, everything after it will be parsed as part of what is above it.

That's bad design in php-fpm, but in the meantime this breaks the php-fpm.conf check every time something is added to it that wasn't present before the include.

Here's an ugly but working workaround:
```yml
- name: Copy the FPM configuration file
  ini_file: dest={{ php_fpm_conf }} section="{{ item.section }}" option="{{ item.option }}" value="{{ item.value }}" backup=yes
  with_items: fpm_config
  tags: [configuration,php,fpm]

- name: Delete the include line from the ini file
  ini_file: dest={{ php_fpm_conf }} section=global option=include backup=no state=absent
  with_items: fpm_config
  tags: [configuration,php,fpm]

- name: Readd the include line from the ini file
  ini_file: dest={{ php_fpm_conf }} section=global option=include backup=no state=present value="/etc/php5/fpm/pool.d/*"
  with_items: fpm_config
  notify: 
   - restart php-fpm
  tags: [configuration,php,fpm]
```
