### ISSUE TITLE
Can't apply custom config

### ISSUE THREAD

**Issue by deimosfr** [NBZ4live/ansible-php-fpm#7]
Hi,

I'm trying to deploy PHP-FPM custom configuration, however it only deploy the default one. I'd like to override it with custom setting like this:

```
- name: web
  hosts: web
  user: root
  roles:
    - role: nbz4live.php-fpm
      php_fpm_pools:
        - name: www
          user: www-data
          group: www-data
          listen: "{{fpm_sock_path}}"
          listen.mode: 0660
          pm: dynamic
          pm.max_children: 75
          pm.start_servers: 10
          pm.min_spare_servers: 5
          pm.max_spare_servers: 30
          pm.max_requests: 500
          pm.status_path: /fpm_status
          chdir: /
          slowlog: /var/log/php5-fpm.log.slow
          request_slowlog_timeout: 1s
      php_fpm_ini:
        - option: "date.timezone"
          section: "PHP"
          value: "{{timezone}}"
      php_fpm_default_pool:
        delete: yes
        name: www.conf
```

However, it's always the default configuration which is called. Here is what I got:

```
 vagrant provision web1
==> web1: Running provisioner: ansible...

PLAY [web] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [web1]

TASK: [nbz4live.php-fpm | Install the php packages] *************************** 
ok: [web1] => (item=php5-cli,php5-fpm)

TASK: [nbz4live.php-fpm | Copy the PHP configuration file] ******************** 
ok: [web1] => (item={'section': 'PHP', 'option': 'engine', 'value': '1'})
ok: [web1] => (item={'section': 'PHP', 'option': 'error_reporting', 'value': 'E_ALL & ~E_DEPRECATED & ~E_STRICT'})
ok: [web1] => (item={'section': 'ldap', 'option': 'ldap.max_links', 'value': '1'})

TASK: [nbz4live.php-fpm | Copy the FPM configuration file] ******************** 
ok: [web1] => (item={'section': 'global', 'option': 'error_log', 'value': '/var/log/php5-fpm.log'})

TASK: [nbz4live.php-fpm | Delete the default POOL configuration file] ********* 
ok: [web1]

TASK: [nbz4live.php-fpm | Copy the POOL configurations] *********************** 
ok: [web1] => (item={'pool': {'name': 'foo', 'vars': ['user = www-data', 'group = www-data', 'listen = 8000', 'pm = dynamic', 'pm.max_children = 5', 'pm.start_servers = 2', 'pm.min_spare_servers = 1', 'pm.max_spare_servers = 3', 'chdir = /']}})

TASK: [nbz4live.php-fpm | Check php-fpm syntax of configuration files] ******** 
ok: [web1]

TASK: [nbz4live.php-fpm | Start the php5-fpm service] ************************* 
ok: [web1]

PLAY RECAP ******************************************************************** 
web1                       : ok=8    changed=0    unreachable=0    failed=0   
```

The foo pool configuration is deployed, but not my www one. I tried to change www name without success.

Any idea on what I missed ?

Thanks
